services:
  pwn-launcher:
    container_name: pwn-launcher
    restart: on-failure
    tty: true        # docker run -t
    build:
      context: ./app
    volumes:
      - type: bind
        source: ./input
        target: /app/input
      - type: bind
        source: ./output
        target: /app/output